//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTurn.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> ToiletId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Toilet Toilet { get; set; }
    }
}
